# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Line_Split_Tool
                                 A QGIS plugin
 This Tool splits the line
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-08-13
        copyright            : (C) 2021 by me
        email                : me
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Line_Split_Tool class from file Line_Split_Tool.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .line_split_tool import Line_Split_Tool
    return Line_Split_Tool(iface)
